### ISSUE TITLE
Travis CI build failing on 'rake db:create:all' step

### ISSUE THREAD

**Issue by mattlindsey** [strawberrycanyon/redeemify#39]
```$ bundle exec rake db:create:all
bundler: failed to load command: rake (/home/travis/build/mattlindsey/redeemify/vendor/bundle/ruby/2.3.0/bin/rake)
Gem::LoadError: You have already activated did_you_mean 1.0.0, but your Gemfile requires did_you_mean 1.0.2. Prepending `bundle exec` to your command may solve this.
  /home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.6/lib/bundler/runtime.rb:40:in `block in setup'
  /home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.6/lib/bundler/runtime.rb:25:in `map'
  /home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.6/lib/bundler/runtime.rb:25:in `setup'
  /home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
  /home/travis/.rvm/gems/ruby-2.3.0@global/gems/bundler-1.13.6/lib/bundler/setup.rb:10:in `<top (required)>'
  /home/travis/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /home/travis/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
The command "bundle exec rake db:create:all" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by mattlindsey** [comment]
It does look like something in the following commit of the CSS change broke the build (as Sam noticed):
https://github.com/strawberrycanyon/redeemify/compare/30646bae1bcc...d78042fc374e

I have sent this info to Travis support, hoping they can help.

**Comment by mattlindsey** [comment]
Fixed by entering issue on github travis ci.  Added 'gem remove did_you_mean' to travis.yml.
